import { ReactNode } from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
interface Props {
  children: ReactNode
  title: string
  colorScheme: 'dark' | 'light'
  paddingTop?: boolean
}
const Layout = (props: Props) => {
  const { children, title, colorScheme, paddingTop } = props

  const dark = colorScheme === 'dark'
  return (
    <div className={`${dark ? 'bg-black text-white' : 'bg-white text-black'}`}>
      <div className="flex flex-col min-h-screen">
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💙</text></svg>"
          />
        </Head>

        <Navbar sitename="ONJUNO" colorScheme={colorScheme} />
        <main className={`flex-1 w-full h-full ${paddingTop && 'pt-20'}`}>
          {children}
        </main>
      </div>
      <Footer />
    </div>
  )
}

export default Layout
